export const assets = [
  // ===== CRYPTOCURRENCIES =====
  {
    name: 'Bitcoin',
    symbol: 'BTC-USD',
    color: '#f7931a',
    bottomDate: '2022-11-21',
    bottomPrice: 15500,
    topMode: 'auto',
    topDate: null,
    category: 'CRYPTO',
  },
  {
    name: 'Ethereum',
    symbol: 'ETH-USD',
    color: '#627eea',
    bottomDate: '2022-06-18',
    bottomPrice: 880,
    topMode: 'auto',
    topDate: null,
    category: 'CRYPTO',
  },
  {
    name: 'Solana',
    symbol: 'SOL-USD',
    color: '#9945ff',
    bottomDate: '2022-12-29',
    bottomPrice: 8,
    topMode: 'auto',
    topDate: null,
    category: 'CRYPTO',
  },
  {
    name: 'BNB',
    symbol: 'BNB-USD',
    color: '#f3ba2f',
    bottomDate: '2022-06-18',
    bottomPrice: 183,
    topMode: 'auto',
    topDate: null,
    category: 'CRYPTO',
  },

  // ===== TECH STOCKS =====
  {
    name: 'NVIDIA',
    symbol: 'NVDA',
    color: '#76b900',
    bottomDate: '2022-10-14',
    bottomPrice: 11.2,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Tesla',
    symbol: 'TSLA',
    color: '#cc0000',
    bottomDate: '2023-01-06',
    bottomPrice: 101,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Google',
    symbol: 'GOOGL',
    color: '#4285f4',
    bottomDate: '2022-11-03',
    bottomPrice: 83,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Coinbase',
    symbol: 'COIN',
    color: '#0052ff',
    bottomDate: '2023-01-06',
    bottomPrice: 31,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Robinhood',
    symbol: 'HOOD',
    color: '#00c805',
    bottomDate: '2022-06-16',
    bottomPrice: 7,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Apple',
    symbol: 'AAPL',
    color: '#a2aaad',
    bottomDate: '2023-01-03',
    bottomPrice: 124,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Microsoft',
    symbol: 'MSFT',
    color: '#00a4ef',
    bottomDate: '2022-11-04',
    bottomPrice: 213,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Amazon',
    symbol: 'AMZN',
    color: '#ff9900',
    bottomDate: '2022-12-28',
    bottomPrice: 81,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },
  {
    name: 'Meta',
    symbol: 'META',
    color: '#0668e1',
    bottomDate: '2022-11-03',
    bottomPrice: 88,
    topMode: 'auto',
    topDate: null,
    category: 'TECH',
  },

  // ===== CHINA TECH =====
  {
    name: 'Alibaba',
    symbol: 'BABA',
    color: '#ff6a00',
    bottomDate: '2022-10-24',
    bottomPrice: 60,
    topMode: 'auto',
    topDate: null,
    category: 'CHINA',
  },
  {
    name: 'Tencent',
    symbol: '0700.HK',
    color: '#25d366',
    bottomDate: '2022-10-25',
    bottomPrice: 198,
    topMode: 'auto',
    topDate: null,
    category: 'CHINA',
  },
  {
    name: 'Xiaomi',
    symbol: '1810.HK',
    color: '#ff6700',
    bottomDate: '2022-10-31',
    bottomPrice: 8,
    topMode: 'auto',
    topDate: null,
    category: 'CHINA',
  },

  // ===== PRECIOUS METALS =====
  {
    name: 'Gold',
    symbol: 'GC=F',
    color: '#ffd54f',
    bottomDate: '2022-09-28',
    bottomPrice: 1620,
    topMode: 'auto',
    topDate: null,
    category: 'METALS',
  },
  {
    name: 'Silver',
    symbol: 'SI=F',
    color: '#c0c0c0',
    bottomDate: '2022-09-01',
    bottomPrice: 17.4,
    topMode: 'auto',
    topDate: null,
    category: 'METALS',
  },

  // ===== CONSUMER =====
  {
    name: 'Pop Mart',
    symbol: '9992.HK',
    color: '#ff6b9d',
    bottomDate: '2022-10-28',
    bottomPrice: 9.95,
    topMode: 'auto',
    topDate: null,
    category: 'CONSUMER',
  },
]

// Data range for fetching
export const DATA_START = '2018-01-01'
export const DATA_END = new Date().toISOString().split('T')[0]
