/**
 * Load all asset price data from the static data.json bundle.
 * This file is pre-generated by scripts/fetch-data.js at build time.
 */
let cachedPayload = null

async function loadStaticData() {
  if (cachedPayload) return cachedPayload
  const resp = await fetch('/data.json')
  if (!resp.ok) throw new Error(`Failed to load data.json: ${resp.status}`)
  cachedPayload = await resp.json()
  return cachedPayload
}

/** Fetch all assets — returns [{ asset, raw }] from the static bundle */
export async function fetchAllPrices(assets) {
  const payload = await loadStaticData()
  return assets.map(asset => {
    const rows = payload.bySymbol[asset.symbol] || []
    // Compact format: [date, high, low, close] → expand to objects
    const raw = rows.map(r => ({
      date: r[0],
      high: r[1],
      low: r[2],
      close: r[3],
    }))
    return { asset, raw }
  })
}

/**
 * Normalize prices to percentage change from bottomPrice.
 * Also auto-detect top (ATH after bottom date).
 */
export function processAsset(asset, rawData) {
  // Use configured bottomDate, but get actual low price from Yahoo data
  const configBottomTime = new Date(asset.bottomDate).getTime()
  let bottomDate = asset.bottomDate
  let bp = asset.bottomPrice
  let minDist = Infinity
  for (const d of rawData) {
    const dist = Math.abs(new Date(d.date).getTime() - configBottomTime)
    if (dist < minDist) {
      minDist = dist
      bottomDate = d.date
      bp = d.low
    }
  }

  const bottomTime = new Date(bottomDate).getTime()

  // Normalize all data points (use close for the line, but keep high/low)
  const data = rawData.map(d => ({
    date: d.date,
    price: d.close,
    high: d.high,
    low: d.low,
    pct: ((d.close - bp) / bp) * 100,
    highPct: ((d.high - bp) / bp) * 100,
    timestamp: new Date(d.date).getTime(),
  }))

  // Find top using high price (most precise)
  let topDate, topPrice, topPct
  if (asset.topMode === 'auto') {
    // Auto: find highest high after bottom
    let maxHighPct = -Infinity
    for (const d of data) {
      if (d.timestamp >= bottomTime && d.highPct > maxHighPct) {
        maxHighPct = d.highPct
        topDate = d.date
        topPrice = d.high
        topPct = d.highPct
      }
    }
  } else {
    // Manual: find highest high on topDate
    const topTime = new Date(asset.topDate).getTime()
    let closest = null, minDist = Infinity
    for (const d of data) {
      const dist = Math.abs(d.timestamp - topTime)
      if (dist < minDist) {
        minDist = dist
        closest = d
      }
    }
    if (closest) {
      topDate = closest.date
      topPrice = closest.high
      topPct = closest.highPct
    }
  }

  const peaked = asset.topMode === 'manual'

  // === Previous bear cycle: find peak BEFORE bottom (using high) ===
  let prevTopDate, prevTopPrice, prevTopPct
  let maxPreBottomHigh = -Infinity
  for (const d of data) {
    if (d.timestamp < bottomTime && d.high > maxPreBottomHigh) {
      maxPreBottomHigh = d.high
      prevTopDate = d.date
      prevTopPrice = d.high
      prevTopPct = d.highPct
    }
  }
  const prevTopTime = prevTopDate ? new Date(prevTopDate).getTime() : 0

  // Previous bear: drawdown from pre-bottom peak
  const prevBearDrawdown = prevTopPrice ? ((bp - prevTopPrice) / prevTopPrice) * 100 : 0

  // === Previous bull cycle: find lowest low BEFORE prevTop ===
  let prevBottomDate, prevBottomPrice
  let lowestPrePrevTop = Infinity
  for (const d of data) {
    if (d.timestamp < prevTopTime && d.low < lowestPrePrevTop) {
      lowestPrePrevTop = d.low
      prevBottomDate = d.date
      prevBottomPrice = d.low
    }
  }

  // Previous bull: gain from prevBottom to prevTop
  const prevBullGain = (prevBottomPrice && prevTopPrice) ? ((prevTopPrice - prevBottomPrice) / prevBottomPrice) * 100 : 0

  // === Current bear cycle: drawdown from top to current ===
  const enrichedData = data.map(d => ({
    ...d,
    bearPct: topPrice ? ((d.price - topPrice) / topPrice) * 100 : 0,
    prevBearPct: prevTopPrice ? ((d.price - prevTopPrice) / prevTopPrice) * 100 : 0,
    prevBullPct: prevBottomPrice ? ((d.price - prevBottomPrice) / prevBottomPrice) * 100 : 0,
  }))

  // Current drawdown (last data point)
  const lastPoint = enrichedData[enrichedData.length - 1]
  const currentDrawdown = lastPoint ? lastPoint.bearPct : 0

  // First available data date (for new stock detection)
  const firstDataDate = rawData.length ? rawData[0].date : null

  return {
    ...asset,
    bottomDate,
    bottomPrice: bp,
    data: enrichedData,
    topDate,
    topPrice,
    topPct,
    peaked,
    currentDrawdown,
    prevTopDate,
    prevTopPrice,
    prevBearDrawdown,
    prevBottomDate,
    prevBottomPrice,
    prevBullGain,
    firstDataDate,
  }
}
